### PR TITLE
Fix: Add STEM-Diverse-TV-CMS in the projects list

### LINKED ISSUE #228: Bug: Add STEM diverse tv cms to projects list
### Describe the bug
Although [stem-diverse-tv-cms](https://github.com/anitab-org/stem-diverse-tv-cms) is actively developed, still it is not listed in the projects list

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Click on Projects
3. Scroll down

### Expected behavior
[stem-diverse-tv-cms](https://github.com/anitab-org/stem-diverse-tv-cms) should also be listed in the projects list.

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

### Smartphone (please complete the following information):
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

### PR DESCRIPTION
**Pull request by Rahulm2310**
### Description

Add STEM-Diverse-TV-CMS in the projects list

Fixes #228 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
image

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@keshakaneria @nandini45 Can you please review this PR. Thanks 🙂

**Review by shades-7 — APPROVED** [review]
This looks nice :sparkles: . good work @Rahulm2310

File: src/content/projects_content.js [hunk 1]
```diff
@@ -344,6 +344,34 @@ const projects = {
...
+        {
+          image: {
+            source: require('./../assets/placeholder.png'),
+          },
+          title: 'Stem Diverse TV CMS',
+          description:
+            'CMS for managing content of STEM Diverse TV, an app which provides inspiring, motivating, supportive, educational and informative videos to promote and increase diversity in STEM.',
+          labels: [
+            { title: 'react js', color: '#BD6AAA' },
+            { title: 'javascript', color: '#F9D507' },
```
Comment (HeroicHitesh) [inline src/content/projects_content.js:357]: @Rahulm2310 We are actually using `Typescript` in the `Stem Diverse TV CMS` project. So, IG it would be better to replace `Javascript` with `Typescript`.

**Review by HeroicHitesh — CHANGES_REQUESTED** [review]

**Review by keshakaneria — APPROVED** [review]
It looks great! 🎉

**Review by isabelcosta — APPROVED** [review]
Thank you for working on this @Rahulm2310 ! 🙌🏾
